spring:
 datasource:
  url: jdbc:mysql://localhost/onetwo?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: 1234
 jpa:
   show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL57Dialect
 security:
    user:
      name: admin
      password: admin
   
  
server:
 port: 8086

 